[package]
name = "zenoh_msg_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.148", features = ["derive"]}
serde_json = "1.0.41"

zenoh = "0.7.0-rc"

async-std = "1.12.0"